# Generated by Django 3.1.4 on 2020-12-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=225)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=10)),
                ('matricule', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='useravatar.png', upload_to='myadmin/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
