# Generated by Django 3.1.4 on 2020-12-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=255)),
                ('enseignant', models.IntegerField(default=1)),
                ('matricule', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(default='useravatar.png', upload_to='administrateur/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificattravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('emploi', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('etat', models.CharField(default='En attente', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travailprof', to='demande.professeur')),
            ],
            options={
                'verbose_name': 'Certificat de travail',
                'verbose_name_plural': 'Certificats de travail',
            },
        ),
        migrations.CreateModel(
            name='Certificatprisetravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('emploi', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('etat', models.CharField(default='En attente', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prisetravailprof', to='demande.professeur')),
            ],
            options={
                'verbose_name': 'attestation de prise de travail',
                'verbose_name_plural': 'attestations de prise de travail',
            },
        ),
        migrations.CreateModel(
            name='Attestationconge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('motif', models.CharField(max_length=255)),
                ('etat', models.CharField(default='En attente', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congeprof', to='demande.professeur')),
            ],
            options={
                'verbose_name': 'attestation de congé',
                'verbose_name_plural': 'attestations de congé',
            },
        ),
    ]
