# Generated by Django 3.1.4 on 2021-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0005_auto_20201221_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_demande', models.CharField(choices=[('travail', 'travail'), ('service', 'service'), ('conge', 'conge')], max_length=255)),
                ('demande_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notiprof', to='demande.professeur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
