# Generated by Django 3.1.4 on 2021-01-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationconge',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Traité', 'Traité'), ('Annulé', 'Annulé')], default='En attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatpriseservice',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Traité', 'Traité'), ('Annulé', 'Annulé')], default='En attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificattravail',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Traité', 'Traité'), ('Annulé', 'Annulé')], default='En attente', max_length=255),
        ),
    ]
