# Generated by Django 3.1.4 on 2021-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0007_auto_20210116_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='annee_de_prise_de_travail',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
